### ISSUE TITLE
npm i passport-faceit wont work.

### ISSUE THREAD

**Issue by 18TB** [Technoblazed/passport-faceit#3] opened 2021-06-18 22:50 UTC
Whenever i run "npm install passport-faceit" it doesn't install it and instead logs an error saying:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/Technoblazed/passport-oauth2.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

The document on the official npm site says it is as easy as just npm installing it, however this is not working for me. Can you tell me what the issue could be and how to resolve it? As this is needed for a server with 27k members.

**Comment by Technoblazed** [comment] 2021-06-18 22:53
Duplicate of #2

**Closed as completed by Technoblazed** 2021-06-18 22:53 UTC
